#!/usr/bin/env bash
export LC_ALL=C

apk_path=$1

adb-devices-all | while read _ os_ver model serial
do
    echo "===== Android ${os_ver} / ${model} / ${serial} ====="
    adb -s ${serial} install -r ${apk_path} < /dev/null
done
