#!/usr/bin/env bash
export LC_ALL=C

shotdate=$(date +'%Y%m%d_%H%M%S')

adb-devices-all | while read _ os_ver model serial
do
    _adb_screenshot ${os_ver} ${model} ${serial} ${shotdate} < /dev/null
done

# https://stackoverflow.com/questions/7411052/bash-while-loop-iterates-only-once-whenever-body-contains-ssh
# https://stackoverflow.com/questions/74525164/while-loop-in-bash-script-execute-only-once
