#!/usr/bin/env bash
set -e -o pipefail
export LC_ALL=C

# SCREENSHOT_DIR=~/Desktop
SCREENSHOT_DIR=$(defaults read com.apple.screencapture location)

serial="$1"

source _adb_device_metadata "${serial}"

shotdate=$(date +'%Y%m%d_%H%M%S')
output=${SCREENSHOT_DIR/#\~/$HOME}/Screenshot_${shotdate}_Android${os_ver}_${model}.png

adb -s ${serial} shell screencap -p /sdcard/screen.png
adb -s ${serial} pull /sdcard/screen.png ${output}
adb -s ${serial} shell rm /sdcard/screen.png

echo "Output: ${output}"
