#!/usr/bin/env bash
set -e -o pipefail
export LC_ALL=C

if [[ -z "$1" ]]; then
    read _ os_ver model serial <<< $(adb-devices-all | head -n1)
else
    read _ os_ver model serial <<< $(adb-devices-all | fgrep "$1")
fi

[[ -z "${serial}" ]] && exit 1

shotdate=$(date +'%Y%m%d_%H%M%S')

_adb_screenshot ${os_ver} ${model} ${serial} ${shotdate}
