#!/usr/bin/env bash
set -e -o pipefail
export LC_ALL=C

# SCREENSHOT_DIR=~/Desktop
SCREENSHOT_DIR=$(defaults read com.apple.screencapture location)

if [[ -z "$1" ]]; then
    read _ os_ver model serial <<< $(adb-devices-all | head -n1)
else
    read _ os_ver model serial <<< $(adb-devices-all | fgrep "$1")
fi

[[ -z "${serial}" ]] && exit 1

shotdate=$(date +'%Y%m%d_%H%M%S')
output=${SCREENSHOT_DIR/#\~/$HOME}/Record_${shotdate}_Android${os_ver}_${model}.mp4

scrcpy -s "${serial}" --no-audio --record="${output}"
