#!/usr/bin/env bash
set -e -o pipefail
export LC_ALL=C

# SCREENSHOT_DIR=~/Desktop
SCREENSHOT_DIR=$(defaults read com.apple.screencapture location)

serial="$1"

source _adb_device_metadata "${serial}"

shotdate=$(date +'%Y%m%d_%H%M%S')
output=${SCREENSHOT_DIR/#\~/$HOME}/Record_${shotdate}_Android${os_ver}_${model}.mp4

scrcpy -s "${serial}" --no-audio --record="${output}"
